sudo: required
services:
  - docker

before_install: #build dev version
  - docker build -t calvinj89/react-test -f ./client/Dockerfile.dev ./client
  
script: #testing section
  - docker run -e CI=true calvinj89/react-test npm test
 
after_succes: #build production version
 - docker build -t calvinj89/multi-client ./client
 - docker build -t calvinj89/multi-nginx  ./nginx
 - docker build -t calvinj89/multi-server ./server
 - docker build -t calvinj89/multi-worker ./worker 
 # Log into the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push them to docker hub
 - docker push calvinj89/multi-client
 - docker push calvinj89/multi-nginx
 - docker push calvinj89/multi-server
 - docker push calvinj89/multi-worker
  